name: Compile, test, deploy 
on: [ "push" ]
env: 
  SPRING_DATASOURCE_URL: ${{ secrets.spring_datasource_url }}
  SPRING_DATASOURCE_USERNAME: ${{ secrets.spring_datasource_username }}
  SPRING_DATASOURCE_PASSWORD: ${{ secrets.spring_datasource_password }}
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${{ secrets.spring_jpa_properties_hibernate_dialect }}
  SPRING_JPA_HIBERNATE_DDL-AUTO: ${{ secrets.spring_jpa_hibernate_ddl-auto }}
jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo
      uses: actions/checkout@v3
    - name: Setup Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: '3.8.4'
    - name: Run test
      run: mvn clean verify
    - name: Generate coverage badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-coverage-badge: true
    - name: Upload coverage badge to DigitalOcean spaces
      uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.access_key }}
        secret_key: ${{ secrets.secret_key }}
        space_name: sandbucket
        space_region: sgp1
        source: .github/badges/jacoco.svg
        out_dir: coverage/${{ github.event.repository.name }}
        permission: public-read
    - name: Upload coverage report
      uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.access_key }}
        secret_key: ${{ secrets.secret_key }}
        space_name: sandbucket
        space_region: sgp1
        source: target/site/jacoco
        out_dir: coverage/${{ github.event.repository.name }}/report